### ISSUE TITLE
chromiumcontent.dll size is very small after building on windows

### ISSUE THREAD

**Issue by rock59** [atom/libchromiumcontent#109]
Hi

I need to port my CEF based application and use libchromiumcontent instead of CEF.

I tried to build libchromiumcontent in windows. Everything worked fine with no error but size of chromiumcontent.dll is very small !
(79 KB in out\Release_x64 and 21 KB in out_component\Release_x64)

Also , there is a content.dll (32 MB) alongside with the rest of chromium dlls in out_component\Release_x64 but not in out\Release_x64

I tried several times with both 41.0.2272.76 and 42.0.2311.107 (Debug and Release , 32 and 64) , master and atom branch of libchromiumcontent..
 
How can I build an standalone chromiumcontent.dll same as the one that is distributed with Atom editor?

**Comment by zcbenz** [comment]
From #98 we have changed how libchromiumcontent is built, currently chromiumcontent.dll is just a dummy target and you have to ship all the dlls.
