### ISSUE TITLE
is it safe, legal to use chromiumcontent.dll directly from atom editor release in our own apps

### ISSUE THREAD

**Issue by JerryYangJin** [atom/libchromiumcontent#116]
i would prefer pre-build libchromiumcontent with all of these together(#113), and i was just wondering is it safe and legal to use tools like dumpbin to generate link lib from chromiumcontent.dll in atom editor release.

in this way, we only need to get the header files, then use libchromiumcontent in our own programs.

thanks!

**Comment by paulcbetts** [comment]
This is legal to do, everything is MIT licensed
