### ISSUE TITLE
script/update SSL download error

### ISSUE THREAD

**Issue by pusateri** [atom/libchromiumcontent#118]
With the later versions of Python 2.7.x, more strict SSL checking is performed. I'm getting this error when running script/update

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

Here is a workaround to disable SSL checking. This probably isn't a good long term fix though:

https://gist.github.com/pusateri/3cba128f8ff0edd3dcb1

**Comment by zcbenz** [comment]
This problem doesn't show any more in recent versions.
