### ISSUE TITLE
Dependency instructions in README file

### ISSUE THREAD

**Issue by glaudiston** [atom/libchromiumcontent#131]
Hi, 
I'm trying to build libchromiumcontent in a docker centos7, I had a sad work try-fail build to detect/install all dependencies.
I think it can be so ease for others users if you add this instruction to read me file:

    yum install -y pciutils-devel git tar gcc pkg-config atk-devel pulseaudio-libs-devel gdk-devel gdk-pixbuf2-devel gdk-pixbuf2 pygtk2-devel libXtst-devel libXScrnSaver-devel dbus-devel GConf2-devel libgnome-keyring-devel libexif-devel gperf 

After it I was able to build.

**Comment by zcbenz** [comment]
It has been added to README, thanks!
