### ISSUE TITLE
Add Chromium license file?

### ISSUE THREAD

**Issue by bpasero** [atom/libchromiumcontent#137]
Would it be possible to include the license information of third party libraries used by chromium in this repo? There seems to be a python command [1] to generate the license information.

The rationale is that for VS Code when we consume Electron we need to include the full license information of Chromium and its third party libraries. Currently this is a very manual process for us and ideally this is just provided through libchromiumcontent.

[1] https://src.chromium.org/svn/trunk/src/tools/licenses.py

**Comment by bpasero** [comment]
@zcbenz thanks, much appreciated!

**Comment by bpasero** [comment]
@zcbenz I am trying to find the LICENSES.chromium.html file in the drops of Electron but can not find it. Where to do you generate the license file these days?

**Comment by hokein** [comment]
The `LICENSE.chromium.html` is located in `electron-src-dir/vendor/brightray/vendor/download/libchromiumcontent/` if you use Electron.

**Comment by bpasero** [comment]
@hokein I assume that gets created when I build Electron from source but is not available as download?

**Comment by hokein** [comment]
@bpasero No, it is in the `libchromium.zip` or `libchromiumcontent-static.zip` dist, see https://github.com/atom/libchromiumcontent/blob/master/script/create-dist#L186

**Comment by bpasero** [comment]
@hokein sorry, but I looked anywhere in electron, brightray, libchromiumcontent for downloads that would include the file and I dont find it. I appreciate if I can get a link to the zip to download.

**Comment by hokein** [comment]
@bpasero It's weird. Which version of Electron are you using? Normally the Electron's `boostrap.py` will download the respective `libchromiumcontent.zip` or `libchromiumcontent-static.zip` for you.

You can download the latest `libchromiumcontent.zip` for OS X used in Electron's master branch in
http://github-janky-artifacts.s3.amazonaws.com/libchromiumcontent/osx/x64/8c7f5b9adb9372130a9295b7e0fb19355f613cf9/libchromiumcontent.zip

**Comment by bpasero** [comment]
@hokein thanks, the link is very useful as I can just put in the commit of libchromiumcontent I am interested in to download it.

I can also confirm that the file shows up when I run "boostrap.py" after cloning Electron. It just takes very long until it eventually shows up :)

**Comment by zcbenz** [comment]
@bpasero I forgot to add it to Electron's distribution, it is now included by https://github.com/atom/electron/pull/2847.

**Comment by bpasero** [comment]
Thanks!

**Comment by bpasero** [comment]
@zcbenz I am looking at the contents of the Windows 64 bits 0.34.1 release of Electron and was not being able to find LICENSES.chromium.html in the zip. Any idea where to find it from a Electron release?

**Comment by zcbenz** [comment]
Oops, the PR copied the to Electron, but didn't include it in the final zip file, will fix it in next release.

**Comment by bpasero** [comment]
@zcbenz excellent!
