### ISSUE TITLE
pdf.lib is not created during build and is not packaged during create-dist

### ISSUE THREAD

**Issue by frankhale** [atom/libchromiumcontent#139]
I've noticed that pdf.lib is missing after building and it won't be available to be packaged into dist via create-dist. As an interim fix I've just included it from the official build of libchromiumcontent.

**Comment by frankhale** [comment]
It seems to be missing from static_library after creating dist. This is where I dump a copy of it from the official packaged libchromiumcontent distribution.

**Comment by hokein** [comment]
@frankhale, there are no `pdf.lib` for both `static_library` and `dynamic_library` builds. Instead, we use `pdf.dll` library.

**Comment by frankhale** [comment]
It's not me complaining idly, it's that Electron complains that it's missing so I have to copy it into my custom compiled libchromiumcontent when compiling Electron against it.

**Comment by frankhale** [comment]
It is actually missing from the static dir after compiling libchromiumcontent and creating a dist. It's not there yet it is there in the official distribution of libchromiumcontent.

**Comment by frankhale** [comment]
Now that I'm compiling Electron 0.28.3 against my custom libchromiumcontent the problem has gone away. Electron is no longer complaining that pdf.lib is missing from the static_library of libchromiumcontent.
