### ISSUE TITLE
Missing chrome v45 tag and release

### ISSUE THREAD

**Issue by aspoon** [atom/libchromiumcontent#155]
`electron` has upgraded to `Chrome v45` since version `0.32.0`, but the corresponding tag/release cannot be found in `libchromiumcontent`.

**Comment by frankhale** [comment]
My reply is off topic but does create-dist work for you when you build? https://github.com/atom/libchromiumcontent/issues/154

**Comment by aspoon** [comment]
Almost the same error as you have in #154 except for the actual file in the last line:

`IOError: [Errno 2] No such file or directory: '[...]\\libchromiumcontent\\vendor\\chromium\\src\\out\\Release_x64\\content_shell.pak'`

**Comment by aspoon** [comment]
`create_dist` in `libchromiumcontent` seems to work fine for me -- I have yet to try integrating the output into `electron`.

As for my original issue, I notice that `libchromiumcontent` has had tags pointing to different versions of `chromium`.  It's just a minor issue that I don't see the tag/release anywhere.  I suppose it still works as the commit hash referenced from `electron` is correct.

**Comment by zcbenz** [comment]
We have a tag on v45 now.
