### ISSUE TITLE
video and audio tag are not supported

### ISSUE THREAD

**Issue by zcbenz** [atom/libchromiumcontent#16]
You can visit http://html5test.com to see how well video and audio are supported in current browser.

**Comment by robertoandrade** [comment]
I'm up to suppose to provide `ffmpegsumo.so` somehow? in my structure it doesn't seem to be there after following the instructions to build the example.

**Comment by robertoandrade** [comment]
In my case it fails to build as it can't find `ffmpegsumo.so` in the `vendor` tree:

```
PBXCp vendor/brightray/vendor/download/libchromiumcontent/Release/ffmpegsumo.so /Users/robertoandrade/Library/Developer/Xcode/DerivedData/brightray_example-dcbbgpmbchnadlfhxbqzjduovbav/Build/Products/Debug/Brightray\ Example\ Framework.framework/Versions/A/Libraries/ffmpegsumo.so
    cd /Users/robertoandrade/Documents/workspace.cloud.rnd/brightray_example
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/robertoandrade/Documents/workspace.cloud.rnd/brightray_example/vendor/brightray/vendor/download/libchromiumcontent/Release/ffmpegsumo.so /Users/robertoandrade/Library/Developer/Xcode/DerivedData/brightray_example-dcbbgpmbchnadlfhxbqzjduovbav/Build/Products/Debug/Brightray\ Example\ Framework.framework/Versions/A/Libraries
```

**Comment by frankhale** [comment]
@robertoandrade, if you are building the latest libchromiumcontent that uses Chrome 44 then ffmpeg is now built statically. You won't find a DLL/shared object for it.

**Comment by robertoandrade** [comment]
I checked out and the `VERSION` file says `44.0.2403.125`. The problem seems to be with the Brightray Example as it's referencing the .so as something to copy during the build phase: `vendor/brightray/vendor/download/libchromiumcontent/Release/ffmpegsumo.so`

**Comment by frankhale** [comment]
Yeah the Brightray example hasn't been updated as far as I can tell. I tried it out a few weeks ago but it would not build for me.

**Comment by robertoandrade** [comment]
Yeah, I opened an issue against the example project (https://github.com/atom/brightray_example/issues/28), hoping to get some feedback there.

**Comment by hokein** [comment]
@robertoandrade 
As @frankhale said above, the `brightray_example` is kind of out-of-date, only work under Chrome 40. So you can't build it with Chrome 44 due to the bunch of API changed in Chrome 44.
