### ISSUE TITLE
Upgrade to Chromium 46.0.2490.80

### ISSUE THREAD

**Issue by romaincointepas** [atom/libchromiumcontent#161]
http://googlechromereleases.blogspot.hk/2015/10/stable-channel-update_22.html

Building chromium 45 on a Mac with latest stable Xcode (7.0) is throwing so many errors, it's just impossible to monkey patch (here is one of them: https://chromium.googlesource.com/chromium/src/+/32dc9ad4eccdb86943b100a2741d8591f712ab0c).

Luckily, they've fixed all of these in 46!

**Comment by zcbenz** [comment]
We are current blocked by non-techniqual reasons, you can find more about it https://github.com/atom/electron/issues/3312#issuecomment-153632338.

**Comment by LukePulverenti** [comment]
Looks like Chrome 47 has gone stable!
