### ISSUE TITLE
Broken aspect ratio for Netflix

### ISSUE THREAD

**Issue by romaincointepas** [atom/libchromiumcontent#170]
`electron v0.36.3` introduced the support for the Widevine CDM plugin, which makes Netflix works inside Electron.

However, Chrome 47 (the initial release) shipped with a major bug that makes Netflix videos have a broken ratio (see [screenshot](http://f.cl.ly/items/36321e0h401Y081i0t1v/Screen%20Shot%202016-01-08%20at%207.46.59%20PM.png)).

Chromium pushed a fix pretty quickly but it's not in `libchromiumcontent`.

Here is the [chromium patch](https://codereview.chromium.org/1500713003) and the [extremely small diff](https://chromium.googlesource.com/chromium/src/+/742c06c58e9b3dd0b6e50e8bba84c7d9acfef7ef%5E%21/#F0).

Would it be possible to backport that fix into `libchromiumcontent` and include it in the next electron release? (on my side, the sooner the better).

Also, tell me and I would happily create a PR for this.

Thanks!

**Comment by zcbenz** [comment]
@romaincointepas I'll backport the patch in libchromiumcontent and include it in next release of 0.36.x.

**Comment by romaincointepas** [comment]
Thanks!
