### ISSUE TITLE
Library build instructions fail

### ISSUE THREAD

**Issue by todd-pack** [atom/libchromiumcontent#172]
Building the latest tagged version (v45.0.2454.85) on Ubuntu 14.04-x86_64, following the README.md instructions to build fails with the following:

 ./script/build -t x64
ninja: Entering directory `vendor/chromium/src/out/Release'
ninja: fatal: chdir to 'vendor/chromium/src/out/Release' - No such file or directory
Traceback (most recent call last):
  File "./script/build", line 45, in <module>
    sys.exit(main())
  File "./script/build", line 33, in main
    subprocess.check_call([NINJA, '-C', config_dir] + TARGETS)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/todd/Projects/electron/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'vendor/chromium/src/out/Release', 'chromiumcontent_all']' returned non-zero exit status 1

The only issue in the previous step was that it complained about xscrnsaver, which does not appear in apt-cache search xscrnsaver on the platform. The complaint is this:

No package 'xscrnsaver' found
gyp: Call to 'pkg-config --cflags xscrnsaver' returned exit status 1 while in build/linux/system.gyp.

Otherwise it appears to complete successfully. I would not expect this to cause the build script to fail at the step above.

**Comment by zcbenz** [comment]
The README is probably a bit out of date, you can follow this guide to install dependencies:
https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions_prerequisites.md
