### ISSUE TITLE
code modification & detailed documentation

### ISSUE THREAD

**Issue by Akshay-Thakare** [atom/libchromiumcontent#177]
I am working on building a code integrity checker for Electron apps but I am lost at sea trying to understand the code.

It would be really helpful if you could tell me how atom/browser/api/browser-window.js connects to the cpp code? and Which are the exact processes which start when the electron app is launched?

And 

where can I find detailed documentation of the code in atom/ and chromium_src/ ?

**Comment by zcbenz** [comment]
There is no documentation on the code, the only things helpful are the code comments and code itself.

**Comment by Akshay-Thakare** [comment]
so if someone wants to contribute, then how to go about getting started and understanding where to begin?
