### ISSUE TITLE
libchromiumcontent/Electron is licensed incorrectly, current build is GPL

### ISSUE THREAD

**Issue by MarshallOfSound** [atom/libchromiumcontent#178]
The current build process of electron builds a custom version of chromium through the module [libchromiumcontent][0].  This is all very well but there is a single flag inside this build process found [here][1] that turns your build of chromium into GPL licensed code.  

That flag builds ffmpeg with a whole load of additional codecs which are licensed under GPL.  An example of such a codec is `H.264`.  It has been confirmed that `libchromiumcontent` builds this codec in [this issue][2] and confirmed that it is GPL licensed on [ffmpeg's site][3].  This codec is just one example of a GPL component included in the `ffpmeg` build `libchromiumcontent` generates.  

### Problem

Electron is currently licensed under the [MIT License][4] which is against the terms of GPL.  In lamens terms, anything that uses GPL licensed software must also be GPL licensed.  This is a MASSIVE issue for many companies that use electron to ship commercial grade applications.  It means that any application they ship can be claimed to have to be GPL and they MUST release their source code.

Further evidence of the GPL nature of this build style is found in the `nw.js` documentation [here][5].

### Solution

We would like to request that you ship `non-GPL` versions of the prebuilt electron packages and update your licenses / README to reflect the fact that some packages use GPL licensed software.  

We have attached a PR [here][6] (#179) to help fix this issue.  This PR basically moves the change in [this commit][1] to an environment variable so you can easily turn on / off the GPL version.

[0]: https://github.com/atom/libchromiumcontent
[1]: https://github.com/atom/libchromiumcontent/pull/69/files#diff-2544685f4860e4633fd5747ed88ec2caR6
[2]: https://github.com/atom/libchromiumcontent/issues/174#issuecomment-175297780
[3]: https://www.ffmpeg.org/doxygen/2.6/md_LICENSE.html
[4]: https://github.com/atom/electron/blob/master/LICENSE
[5]: http://docs.nwjs.io/en/v0.13.0-beta5/For%20Developers/Enable%20Proprietary%20Codecs/#enable-proprietary-codecs-in-nwjs
[6]: https://github.com/atom/libchromiumcontent/pull/179

**Comment by paulcbetts** [comment]
The comments in https://github.com/atom/libchromiumcontent/pull/69 seem to explicitly indicate that this isn't true (despite the flag being the same name)

**Comment by MarshallOfSound** [comment]
Those comments are incorrect.  I have verified by manually building electron with that flag turned off and MP3 / H.264 codec support vanishes.  That flag DOES build a GPL version of ffmpeg into electron.

Just checkout the equivalent documentation for `nw.js` [here](http://docs.nwjs.io/en/v0.13.0-beta5/For%20Developers/Enable%20Proprietary%20Codecs/#enable-proprietary-codecs-in-nwjs)

**Comment by zcbenz** [comment]
According to ffmpeg's file:

> Some optional parts of FFmpeg are licensed under the GNU General Public License version 2 or later (GPL v2+). See the file COPYING.GPLv2 for details. None of these parts are used by default, you have to explicitly pass --enable-gpl to configure to activate them. In this case, FFmpeg's license changes to GPL v2+.

The GPL code is only enabled when `--enable-gpl` is passed.

You can find Chromium's configuration for ffmpeg at:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/ffmpeg/chromium/config/Chrome/win/x64/config.h&sq=package:chromium

Apparently there is no GPL code used, and the resulting license is "LGPL version 2.1 or later".

The problem with MP3/H.264 codecs is about patent, not about code license.

**Comment by arcticShadow** [comment]
> The GPL code is only enabled when --enable-gpl is passed.

This is not accurate.

From the [FFMPEG site](https://www.ffmpeg.org/general.html#x264) the x264 codec can be enabled with a different flag `--enable-libx264` ( as can many other GPL codecs). The section on h264 also states that the codec, if enabled, changes FFMPEG license to GPLv2.


I note from the FFMPEG docs, the --enable-gpl flag is not the only way that gpl licensing becomes enabled. This is a quote straight from their legal page:

> However, FFmpeg incorporates several optional parts and optimizations that are covered by the GNU General Public License (GPL) version 2 or later. If those parts get used the GPL applies to all of FFmpeg.

Given that the compile time options linked by zcbenz include `--enable-decoder='aac,h264,mp3' --enable-demuxer='aac,mp3,mov' --enable-parser='aac,h264,mpegaudio'` it seems pretty clear that FFMPEG is compile using parts of GPL licensed components. 

To prove a point (that h264 is enabled in Electron by default) I encourage you to open any electron app, and open the inspector with `CMD + OPTION + I` (on a mac) and type the following into the console, followed by the enter key. `window.location = "http://download.openbricks.org/sample/H264/h264_Linkin_Park-Leave_Out_All_The_Rest.mp4"` If electron is not under GPL, then this H264 file, with AAC audio encoding will not play.  Of course, you are free to test with your own H264 resources as well.

**Comment by paulcbetts** [comment]
>  If electron is not under GPL, then this H264 file, with AAC audio encoding will not play. Of course, you are free to test with your own H264 resources as well.

I don't know that this is accurate, because Chrome will use installed system codecs depending on the platform

**Comment by MarshallOfSound** [comment]
I can immediately disprove the idea that

> Chrome will use installed system codecs

With this simple setup.  I am on a Mac running OSX 10.11.2.  Navigated to this page  
http://www.leanbackplayer.com/test/h5mt.html

In **Chromium** <-- Take note this is not chrome
![screen shot 2016-02-16 at 12 18 16 pm](https://cloud.githubusercontent.com/assets/6634592/13062936/c2f59800-d4a7-11e5-9328-41debf795f5f.png)
As you can see it does not support ANY H.264 video formats even though Google Chrome and as you can see here Electron **does**

![screen shot 2016-02-16 at 12 19 15 pm](https://cloud.githubusercontent.com/assets/6634592/13062947/daf2de72-d4a7-11e5-99a2-9a06945bbbec.png)

The screenshot above is from Electrons latest release.

@paulcbetts Can you explain how a GPL licensed codec H.264 (amongst others) is available in electron but not chromium.  If chromium/chrome searches your system for the codecs, why doesn't chromium use them?

This test quite conclusively shows that Electron has baked in GPL licensed codecs

**Comment by paulcbetts** [comment]
> This test quite conclusively shows that Electron has baked in GPL licensed codecs

Seems legit, though I wonder how the GPL would apply here. If you redistribute Electron but with proprietary JavaScript, and if someone requests the source, do you have to provide the Electron source or the app's source?

**Comment by MarshallOfSound** [comment]
@paulcbetts Given that we have now determined electron has GPL components.  Electron itself **becomes** GPL licensed.  That's just how the GPL works.

If the proprietary software is built on Electron, it’s likely to be considered a “work based on the Program” and therefore come under the GPL license as well, in which case the source for the proprietary software would need to be released.  The relative section of the GPL license is [here](http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html#section0)

The solution here is to do what @zcbenz suggested [here](https://github.com/atom/libchromiumcontent/issues/174#issuecomment-184187254) and switch ffmpeg to be dynamically linked but also provide a non-gpl build of electron with that `proprietary_codecs` flag disabled. The PR #179 gave the general direction of that the change would look like

**Comment by zcbenz** [comment]
@arcticShadow Chromium is not using GPL code from ffmepg, you can find the detailed list of ffmpeg source files used by Chromium at:
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/ffmpeg/ffmpeg_generated.gypi&sq=package:chromium 

which doesn't include the [GPL source files](https://www.ffmpeg.org/doxygen/2.6/md_LICENSE.html), or GPL licensed libraries like libx264. Supporting proprietary codecs doesn't necessarily mean we are using GPL source code.

**Comment by simongregory** [comment]
I had the task of going through this a few weeks ago in order to provide our legal team with the technical details on how Electron supports proprietary codecs. Our focus was patent liabilities but I also noticed there could be a GPL issue. 

I originally misinterpreted [Chromiums FFmpeg LICENSE](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/ffmpeg/LICENSE.md&sq=package:chromium&type=cs) and thought proprietary codecs == GPL code (there's also [other examples of this](https://github.com/nwjs/nw.js/blob/nw13/docs/For%20Developers/Enable%20Proprietary%20Codecs.md)). I figured it was likely Google were [commercially licensing x264][http://x264licensing.com] for Chrome to avoid the restrictive obligations of using the library under the [GPL][].

A bit more digging and I couldn't find any GPL licensed code in a built checkout of libchromiumcontent. I then clocked that `libx264` is for ***En***coding, not decoding - hence the separate nature of the `--enable-libx264` flag.

If you want a detailed discussion of the original inclusion in Chromium then check [this whatwg thread](https://lists.w3.org/Archives/Public/public-whatwg-archive/2009Jun/0014.html).

I'm not sure the patent saga is quite over yet, my initial tests are showing playback of h.264 and AAC encoded content with [Electron v0.36.8](https://github.com/atom/electron/releases/tag/v0.36.8), and the libffmpeg.dylib **without** proprietary support. Electron/Chromium is probably letting the request through (as it thinks it supports the mime type) then ffmpeg decodes using the GPU. Probably best I open another issue on this once I've done some more digging/validation.

**Comment by paulcbetts** [comment]
@simongregory The easiest to do might be to just play the content with a debugger attached then break in a few times and see what module you're in.

**Comment by zcbenz** [comment]
@simongregory With replaced ffmpeg library Electron would still assume it can use proprietary codecs, this is because Chromium hardcoded the logics, but the media will fail to play in the final step because there is actually no such codecs. I tested with videos in this page: http://www.quirksmode.org/html5/tests/video.html.
