### ISSUE TITLE
is it possible to build libchromiumcontent out of a regular chromium build ?

### ISSUE THREAD

**Issue by kapouer** [atom/libchromiumcontent#46]
Hi,
i'm trying to answer that question - in debian, it would be nice to be able to have the chromium package build spit out that shared library in the process, so that brightray could (dynamically) link to a libchromiumcontent debian package built out of chromium.
It would avoid maintenance of several versions of chromium.
Thanks for any info.
Jérémy.

**Comment by zcbenz** [comment]
I'm closing this since it is not possible.
