### ISSUE TITLE
Windows Vista support

### ISSUE THREAD

**Issue by MartinMa** [atom/libchromiumcontent#66]
Looking at [atom-shell](https://github.com/atom/atom-shell) it seems (theoretically) to be able to run on Windows Vista (Extended support ends on 11 April 2017). There are two function exports, which Vista can't handle, namely `RegisterTouchWindow ` and `CloseTouchInputHandle `, both in `user32.dll`.

These dependencies seem to stem from `libchromiumcontent`.
You can test it by looking at `chromiumcontent.dll` located at
`atom-shell/vendor/brightray/vendor/download/libchromiumcontent/Release` using the Dependency Walker.

I think it's just a matter of setting `_WIN32_WINNT` and `WINVER` to `0x0600` instead of `0x0602` in the corresponding `.gypi` file. Maybe `brightray.gypi`?

Chromium and Node.js are built to run on Vista. Is there anything that speaks against atom-shell being able to run on it, too? I'm fine with Atom to only support Win7+, but atom-shell is so versatile.

Thoughts?

**Comment by dustinblackman** [comment]
Is this issue still relevant? Or have something else caused Electron to not run on Vista?

**Comment by paulcbetts** [comment]
If those functions are exported, that means someone is using them. While it's probably possible to get Atom Shell to run on Vista, I am :-1: into putting any work into supporting these dead operating systems.

**Comment by zcbenz** [comment]
We don't have plan to support Vista.
