### ISSUE TITLE
error compiling on mac os x

### ISSUE THREAD

**Issue by manang** [atom/libchromiumcontent#685]
Hi,
I have the following error when I try to compile on mac os x:

$ script/build -t x64
ninja: Entering directory `src/out-x64/static_library'
ninja: error: '../../chrome/common/widevine_cdm_constants.cc', needed by 'obj/libchromiumcontent/chromiumcontent/cdm_support/widevine_cdm_constants.o', missing and no known rule to make it
Traceback (most recent call last):
  File "script/build", line 79, in <module>
    sys.exit(main())
  File "script/build", line 52, in main
    run_ninja(os.path.relpath(out_dir), target=target, env=env)
  File "/Users/angelomantellini/libchromiumcontent/script/lib/ninja.py", line 26, in run
    subprocess.check_call(args, env=env)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/angelomantellini/libchromiumcontent/vendor/depot_tools/ninja', '-C', 'src/out-x64/static_library', 'libchromiumcontent/chromiumcontent:chromiumcontent']' returned non-zero exit status 1`

solutions?

**Comment by manang** [comment]
Maybe I have a solution:
I commented
//chrome/common/widevine_cdm_constants.cc in
./chromiumcontent/BUILD.gn,

**Comment by nornagon** [comment]
libchromiumcontent is deprecated, electron now builds chromium as part of itself: https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md

Is there a particular task you're trying to accomplish?

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
