### ISSUE TITLE
howto compile libchromiumcontent 3.0.0 electron

### ISSUE THREAD

**Issue by manang** [atom/libchromiumcontent#687]
Hi,
I want to modify a part of chromium src and I want to use it in electron.
could you tell me the steps that I have to follow to create a new electron distribution?
Thank you

Angelo

**Comment by nornagon** [comment]
https://github.com/electron/electron/blob/3-0-x/docs/development/build-system-overview.md, though the build system for Electron 4.0.x will be very different (see https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md)

**Comment by manang** [comment]
My problem is how to modify libchromiumcontent.
I followed the guide in libchromiumcontent repo, but it is no right.

Il giorno gio 20 set 2018 alle ore 19:12 Jeremy Apthorp <
notifications@github.com> ha scritto:

**Comment by nornagon** [comment]
If you pass `--build_debug_libcc` to bootstrap.py, you'll build a local copy of libchromiumcontent under `vendor/` that you should be able to modify and rebuild by re-bootstrapping. `./script/bootstrap.py -v --build_debug_libcc`

**Comment by manang** [comment]
Hi,
when I bootstrap in this way, is it compiled?
thank you very much for your help

**Comment by nornagon** [comment]
yes, that command will fetch and compile libcc on your machine.
