### ISSUE TITLE
disable_clang still valid?

### ISSUE THREAD

**Issue by Thaodan** [atom/libchromiumcontent#744]
Where did disable_clang from https://github.com/electron/electron/pull/5377/commits/26e4ce30bbcc05290f4ffbd320823414408f9d7a go?
I want to pass it before building electron.

**Comment by nornagon** [comment]
libchromiumcontent is legacy code and only used to build Electron 2 and 3. Additionally, we don't support building without clang. I'm afraid you're on your own here!

**Comment by Thaodan** [comment]
Ah so after 3.x its not needed to pass the option?
Its very said to hear that you focus on clang and ignore GCC.

**Comment by nornagon** [comment]
This is not our decision, we are simply following upstream Chromium.
