### ISSUE TITLE
Compile and ship locales/[lang].pak

### ISSUE THREAD

**Issue by orzFly** [atom/libchromiumcontent#79]
I was curious about why `navigator.language == ""` in atom-shell. After some researches I found this settings requires `locales/[lang].pak` files. I tried to copy the locales folder of a Chromium install into Atom-Shell and it worked as a charm.

* https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/frame/Navigator.cpp&q=navigator%20languages&type=cs&sq=package:chromium&l=138
* https://code.google.com/p/chromium/codesearch#chromium/src/content/renderer/render_view_impl.cc&sq=package:chromium&dr=C&l=2180
* https://code.google.com/p/chromium/codesearch#chromium/src/content/public/common/renderer_preferences.h&sq=package:chromium&dr=C&rcl=1414891227&l=106
* https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/renderer_preferences_util.cc&q=GetString%20kAcceptLanguages&type=cs&sq=package:chromium&l=41
* https://code.google.com/p/chromium/codesearch#search/&q=IDS_ACCEPT_LANGUAGES

**Comment by zcbenz** [comment]
Electron solved the empty `navigator.language` with another approach.
