### ISSUE TITLE
Build fail on yosemite

### ISSUE THREAD

**Issue by cognominal** [atom/libchromiumcontent#85]
building on master 7a3461723d, it fails :

  ../../content/common/gpu/media/vt_video_decode_accelerator.cc:321:42: error: use of undeclared   identifier 'GL_TEXTURE_RECTANGLE_ARB'

This is my first attempt dabbling with libchromium.
I did :  script/bootstrap; script/build

Not yet attempted to compile from a release.

**Comment by zcbenz** [comment]
libchromiumcontent now builds with Yosemite.
