### ISSUE TITLE
Getting the libchromiumcontent more compact in releases.

### ISSUE THREAD

**Issue by lygstate** [atom/libchromiumcontent#95]
merge
chromiumcontent.dll
msvcp120.dll msvcr120.dll vccorlib120.dll
xinput1_3.dll
into chromiumcontent.dll

merge ffmpegsumo.dll msvcp120.dll msvcr120.dll 
into ffmpegsumo.dll

merge content_resources_200_percent.pak
content_shell.pak
ui_resources_200_percent.pak
natives_blob.bin
snapshot_blob.bin
into chromiumcontent.pack

**Comment by zcbenz** [comment]
You should propose it on Chromium project, there is nothing we can do in libchromiumcontent.
