### ISSUE TITLE
Building under GBK ANSI on win7 failed.

### ISSUE THREAD

**Issue by lygstate** [atom/libchromiumcontent#96]
[30/2657] CXX obj\chrome\test\chromedriver\chrome\automation_client_lib.mobile_device_list.obj
FAILED: ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @o
bj\chrome\test\chromedriver\chrome\automation_client_lib.mobile_device_list.obj.rsp /c ..\..\chrome\test\chromedriver\chrome\mobile_device_list.cc /Fo
obj\chrome\test\chromedriver\chrome\automation_client_lib.mobile_device_list.obj /Fdobj\chrome\automation_client_lib.cc.pdb
c:\ci-cor\atom\libchromiumcontent\vendor\chromium\src\chrome\test\chromedriver\chrome\mobile_device_list.cc(134) : error C2017: illegal escape sequenc
e
c:\ci-cor\atom\libchromiumcontent\vendor\chromium\src\chrome\test\chromedriver\chrome\mobile_device_list.cc(134) : error C2059: syntax error : 'string
'
c:\ci-cor\atom\libchromiumcontent\vendor\chromium\src\chrome\test\chromedriver\chrome\mobile_device_list.cc(138) : error C2017: illegal escape sequenc
e
[30/2657] CXX obj\third_party\webrtc\voice_engine\voice_engine.channel_manager.obj

**Comment by zcbenz** [comment]
Recent versions should be building now.
